# Generated by Django 3.1.7 on 2021-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numReview',
            new_name='numReviews',
        ),
    ]
